### ISSUE TITLE
如何置零位？使用过程中发现并不是绝对值编码，每次开机的零位都不一样

### ISSUE THREAD

**Issue by NirViaje** [unitreerobotics/unitree_actuator_sdk#11]
使用过程中发现并不是绝对值编码，每次开机的零位都不一样
https://github.com/xiaoliangstd/unitreeMotor-docs.github.io/issues/5

**Comment by xiaoliangstd** [comment]
你好，电机采用的是单圈绝对值编码器，并且 该编码器是在电机转子端的，所以每次开机零位是不一样的

**Comment by NirViaje** [comment]
> 你好，电机采用的是单圈绝对值编码器，并且 该编码器是在电机转子端的，所以每次开机零位是不一样的

对，我发现了，你们6.33的减速比要自己算，并且像这样的话除非是力矩限位否则没法自己获得输出的零位

**Comment by xiaoliangstd** [comment]
> > 你好，电机采用的是单圈绝对值编码器，并且 该编码器是在电机转子端的，所以每次开机零位是不一样的
> 
> 对，我发现了，你们6.33的减速比要自己算，并且像这样的话除非是力矩限位否则没法自己获得输出的零位

为啥要自己算，手册上有写

**Comment by NirViaje** [comment]
> > > 你好，电机采用的是单圈绝对值编码器，并且 该编码器是在电机转子端的，所以每次开机零位是不一样的
> > 
> > 
> > 对，我发现了，你们6.33的减速比要自己算，并且像这样的话除非是力矩限位否则没法自己获得输出的零位
> 
> 为啥要自己算，手册上有写

是要在代码里自己写19/3

**Comment by xiaoliangstd** [comment]
> > > > 你好，电机采用的是单圈绝对值编码器，并且 该编码器是在电机转子端的，所以每次开机零位是不一样的
> > > 
> > > 
> > > 对，我发现了，你们6.33的减速比要自己算，并且像这样的话除非是力矩限位否则没法自己获得输出的零位
> > 
> > 
> > 为啥要自己算，手册上有写
> 
> 是要在代码里自己写19/3

是的，计算的时候得把减速比给上
