### ISSUE TITLE
Can this SDK be configured for torque limiting?

### ISSUE THREAD

**Issue by KazuyaOguma18** [unitreerobotics/unitree_actuator_sdk#16]
I would like to use go-M8010-6 motors as wheels for a mobile robot. In controlling the control of the wheel, I would like to set the torque limit at the same time as the speed command value or at the start of operation.
Is there any way to do this?

**Comment by xiaoliangstd** [comment]
So sorry, we haven't yet provided the torque limit interface on the motor drive side to the user。

**Comment by KazuyaOguma18** [comment]
Understood. Thank you very much for answering.
