### ISSUE TITLE
运行go-m8010-example时报错：Inappropriate ioctl for device

### ISSUE THREAD

**Issue by 15210579725** [unitreerobotics/unitree_actuator_sdk#17]
感谢您对于电机问题的回答
我们用的是淘宝买的USB转RS485转换器，驱动安装的是CH343，但是在跑example时有如下报错
what():  IO Exception (25): Inappropriate ioctl for device, file /home/unitree/unitree_actuator_sdk-all/src/SerialPort.cpp, line 487.
我们该怎么做

**Comment by 15210579725** [comment]
@xiaoliangstd

**Comment by xiaoliangstd** [comment]
您好，我这边目前还是无法复现出您说的这个问题，我怀疑可能是 sdk 底层代码 对您购买的 usb 转 485模块的芯片进行某些配置操作时，出现问题。这边建议还是使用宇树的usb 转 485模块，或者您可联系我们的技术支持团队要一份 stm32控制宇树电机的代码，尝试使用 stm32进行控制。您也可以发一下您使用的模块的芯片的信息，这边我们尝试分析一下

**Comment by xiaoliangstd** [comment]
这是我们技术支持团队的邮箱 support@unitree.com

**Comment by SUPER-CHAO-19** [comment]
您好，我也遇到同样的问题，三个电机串联使用一个官方的485模块单个电机通信频率达不到1kHz，所有购买一个基于CH348的8路USB转rs485模块希望通过一个电机对应一个ttyUSB的方式来解决上述问题，

驱动安装完后，插入模块显示串口号

![20240523-224621](https://github.com/unitreerobotics/unitree_actuator_sdk/assets/95850911/59d59163-5409-4968-bcd2-2c97b3ca5085)

但是发现改成对应串口号，电机底层串口的SDK不支持该模块进行串口通信，会报出和楼主一样的错误

*********open serial************
terminate called after throwing an instance of 'IOException'
  what():  IO Exception (25): Inappropriate ioctl for device, file /home/liang/Desktop/unitree_actuator_sdk/src/SerialPort.cpp, line 592.
Aborted

模块驱动链接https://www.wch.cn/downloads/CH9344SER_LINUX_ZIP.html  
模块示例代码[GitHub - WCHSoftGroup/tty_uart: linux tty uart application](https://github.com/WCHSoftGroup/tty_uart)

**Comment by 15210579725** [comment]
我们后来用的英国的FTDI的485转换芯片可以成功运行
国产的ch34*确实不太兼容
