### ISSUE TITLE
How to change A1 motor ID?

### ISSUE THREAD

**Issue by yuna-hyu** [unitreerobotics/unitree_actuator_sdk#2]
How to change A1 motor ID?
your code does not work...   : (

**Comment by xiaoliangstd** [comment]
Hello,could you please provide more information? For example, what information does the terminal prompt.

**Comment by yuna-hyu** [comment]
The terminal screen shown in the datasheet appears as follows:

![image](https://user-images.githubusercontent.com/86825634/205294372-00a980c5-e335-4249-bd6c-c8e2caeb7a49.png)

We finished by entering "a" after turning the motor twice. But id is still the same as 0. How do I solve this?

**Comment by OnlineMC** [comment]
Hello @yuna-hyu, Please check :
**example/changeID.cpp:16**@motor_s.motorType = MotorType::B1;    // set the motor type, A1 or B1

If so, please modify it to:
MotorType::B1 -> MotorType::A1
and rebuild it.

**Comment by OnlineMC** [comment]
> Hello @yuna-hyu, Please check : **example/changeID.cpp:16**@motor_s.motorType = MotorType::B1; // set the motor type, A1 or B1
> 
> If so, please modify it to: MotorType::B1 -> MotorType::A1 and rebuild it.



> The terminal screen shown in the datasheet appears as follows:
> 
> ![image](https://user-images.githubusercontent.com/86825634/205294372-00a980c5-e335-4249-bd6c-c8e2caeb7a49.png)
> 
> We finished by entering "a" after turning the motor twice. But id is still the same as 0. How do I solve this?

Hello @yuna-hyu, Please check :
**example/changeID.cpp:16**@motor_s.motorType = MotorType::B1;    // set the motor type, A1 or B1

If so, please modify it to:
MotorType::B1 -> MotorType::A1
and rebuild it.

**Comment by OnlineMC** [comment]
Hello @yuna-hyu, Please check :
**example/changeID.cpp:16**@motor_s.motorType = MotorType::B1;    // set the motor type, A1 or B1

If so, please modify it to:
MotorType::B1 -> MotorType::A1
and rebuild it.

**Comment by xiaoliangstd** [comment]
I'm sorry for this! Tomorrow, I will test this code again to find out what is wrong in your case.

**Comment by yuna-hyu** [comment]
hello:)
Changing the ID was successful!

But.. Is there a Python code that can drive the motor?
Thanks

**Comment by xiaoliangstd** [comment]
in the future Release.it will come soon.
