### ISSUE TITLE
motor receive的信息都是0

### ISSUE THREAD

**Issue by foggyspring** [unitreerobotics/unitree_actuator_sdk#20]
motor receive的信息print后都是0，但是connection好像没有报错。接收到第一个position会运动下。后面就不会动了，这种情况是连接中断了吗，motor还能听到内部声音。

**Comment by xiaoliangstd** [comment]
听您的描述 感觉像是过流了

**Comment by xiaoliangstd** [comment]
这种情况下，你可以把错误标志位打印出来看看，如：  std::cout <<  "motor.merror: " << data.merror <<   std::endl;

**Comment by foggyspring** [comment]
你好，请问过流是什么意思。我把error打印出来都是0

**Comment by foggyspring** [comment]
可以加个微信问问吗

**Comment by xiaoliangstd** [comment]
> 可以加个微信问问吗

可以，可以发邮件给 xiaoliangstd@gmail.com 或者 support@unitree.com
