### ISSUE TITLE
Can you provide an example of force mixed mode for A1 motor?

### ISSUE THREAD

**Issue by tjdalsckd** [unitreerobotics/unitree_actuator_sdk#3]
I want to limit the maximum force of the motor.

>               cmd.T = maxForce;
>               cmd.W = 0.0;
>               cmd.Pos = targetPos;
>               cmd.K_P = 0.1;
>               cmd.K_W = 3.0;

Is it possible to limit it like the method above?

Can you provide an example of force mixed mode for A1 motor?

**Comment by xiaoliangstd** [comment]
Sorry, in this version of firmware, the maximum torque cannot be limited。

**Comment by xiaoliangstd** [comment]
The actual torque generated by the motor can be calculated by this formula：tau = tau_ff + Kp * (q - q_des) + Kd * (qd - qd_des).Here, you can just calculate, but not limit the maximum torque generated by the motor via unitree_actuator_sdk.

**Comment by tjdalsckd** [comment]
Thank you for the response
