### ISSUE TITLE
How to Use Mixed Mode

### ISSUE THREAD

**Issue by yuna-hyu** [unitreerobotics/unitree_actuator_sdk#4]
![image](https://user-images.githubusercontent.com/86825634/208562222-2d66908c-97a0-4f25-80fd-e4251c5835d4.png)

I want to control the mixed mode in the A1 motor datasheet.

For example, I would like to provide torque and position at once.
Could you provide me with an example related to this?

**Comment by xiaoliangstd** [comment]
Usually the mixed model will be used in controlling the actuated joints of a legged robot. 

In such a scenario, the feed-forward torque tau_ff, desired joint position q_des and desired joint velocity qd_des will  be sent to the low level motor together. Then the overall torque is controller as follows: tau = tau_ff + Kp * (q - q_des) + Kd * (qd - qd_des), where Kp, Kd can also be set and tuned on your own. 

Then let's get back to your question, if you wanna only control torque and position, you could kindly set Kd to zero~

**Comment by xiaoliangstd** [comment]
You can refer to this project [https://github.com/mit-biomimetics/Cheetah-Software](url), the WBC controller in this project can output joint torque、joint position 、joint velocity at once.
