### ISSUE TITLE
Is it work for Jetson nano?

### ISSUE THREAD

**Issue by Calmsk02** [unitreerobotics/unitree_actuator_sdk#6]
Hi.
I'm trying to control A1 motor with Jetson nano board (ubuntu20.04).
When I built the code, the following error comes up,
"IOException (2) : No such file or directory, file /home/pi/Desktop/src_unitree_actuator_sdk/src/SerialPort.cpp, line 249."

I think that path is define in the library file, and it is for the Raspberry Pi.
So, my question is,  does this SDK support for jetson nano?
If not, is there any way to control A1 motor with jetson nano?

**Comment by Calmsk02** [comment]
Thanks for reply.
I used the enclosed USB-485 module. 
For the first few seconds, it prints the motor data on the terminal well.
However, after few seconds, the below warnings are shown
'''
[WARNING] SerialPort::recv, unblock version, wait time out
[WARNING] SerialPort::recv, unblock version, received 67 bytes, but not 78 bytes.
'''

And then connection is failed(program aborted) and no more connection with the below error.
'''
IOException (2) : No such file or directory, file /home/pi/Desktop/src_unitree_actuator_sdk/src/SerialPort.cpp, line 249.
'''

After that, I tryed plug in the usb-485 module again. 
Then, it is connected and disconnected after few seconds, again.

I don't know what is the problem....
Thanks for your suggestion. 
I'll try using IO port isolator.

**Comment by xiaoliangstd** [comment]
By the way, what's the voltage and current of your power supply?

**Comment by Calmsk02** [comment]
I'm using 30V/10A one. 
There are no problem when I connect it to my laptop with same configuration. Only Jetson nano has problem..

When I checked communication speed with "stty" command, the speed was 0 baud, while other sensor(like, IMU) showed 9600 baud.
So.. I think it is not the problem with /dev/ttyUSB0 port.

I just guess that the USB-rs485 module is not fit for my jetson, so I'm going to try with other module that enables rs485 communication.

**Comment by Calmsk02** [comment]
And I'll try USB hub or USB-isolator as you suggested.

**Comment by Calmsk02** [comment]
I tried with USB-hub, and the problem solved!!
Still don't understand why It didn't work, by the way, I'm happy now.
Thanks for your kindness :)

**Comment by xiaoliangstd** [comment]
> I tried with USB-hub, and the problem solved!! Still don't understand why It didn't work, anyway, I'm happy now. Thanks for your kindness :)

haha, me too!  that is the solution from hardware engineer.

**Comment by spcrobocar** [comment]
hi @Calmsk02 I am working on a similar project, trying to use Jetson orin to talk to the A1 motor. Could you please tell me what the USB-485 module is?

**Comment by Calmsk02** [comment]
> hi [@Calmsk02](https://github.com/Calmsk02) I am working on a similar project, trying to use Jetson orin to talk to the A1 motor. Could you please tell me what the USB-485 module is?

Hi. 
After some trials, now I'm using U2D2 from ROBOTIS.
I guess, you can use any other devices support rs485 communication.
By the way, here is the link for U2D2. :)
https://www.robotis.us/u2d2/?srsltid=AfmBOor-2cDMNkJCx-y5C7w-qN8G1awwaolc44AfRFMI0GHFaPQhAb9Q
